In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a = np.array([1,2,3,4,5,6,7])
a[0]

1

In [9]:
a[2:5]

array([3, 4, 5])

In [10]:
L = [1,2,3,4,5,6,7]
L[0]

1

In [11]:
L[2:5]

[3, 4, 5]

In [12]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [13]:
L[:6]

[1, 2, 3, 4, 5, 6]

In [14]:
a[3:]

array([4, 5, 6, 7])

In [15]:
a[-1]

7

In [16]:
a[2:-3]

array([3, 4])

In [17]:
a[-5:]

array([3, 4, 5, 6, 7])

In [18]:
a[-5:-1]

array([3, 4, 5, 6])

In [19]:
a[-2:2]

array([], dtype=int64)

In [20]:
np.size(a)

7

In [21]:
np.shape(a)

(7,)

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
a[a[2]]

4

In [24]:
L[L[3]]

5

In [25]:
L.reverse()
L

[7, 6, 5, 4, 3, 2, 1]

In [26]:
sorted(a, reverse=True)

[7, 6, 5, 4, 3, 2, 1]

In [27]:
np.shape(a)

(7,)

In [28]:
a = a.reshape(1,7)
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [29]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [30]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [31]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
L = [[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
a[0,0]

1

In [35]:
L[0][0]

1

[1, 2, 3], แถวที่0
[4, 5, 6], แถวที่1
[7, 8, 9]  แถวที่2

[1, 4, 7], คอลัมที่0
[2, 5, 8], คอลัมที่1
[3, 6, 9]  คอลัมที่2

In [36]:
a[1,:]

array([4, 5, 6])

In [37]:
a[:,-1]

array([3, 6, 9])

In [38]:
a[:,1] = 0
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [39]:
a[1,:] = 0
a

array([[1, 0, 3],
       [0, 0, 0],
       [7, 0, 9]])

In [40]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [41]:
a.shape

(3, 3)

In [42]:
a.size

9

In [43]:
np.size(a,1)

3

In [44]:
a.ndim

2

In [45]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [46]:
np_mix_matrix[:,1]

array(['2', '4', '6'], dtype='<U5')

In [47]:
np.array(np_mix_matrix[:,1], dtype=int)

array([2, 4, 6])

In [48]:
a = np.array(np_mix_matrix[:,1], dtype=int)
a

array([2, 4, 6])

In [49]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
a = np.ones((10))
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
c = np.full((5,5),8)
c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [53]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
c*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [55]:
np.matmul(c,d)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [56]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [57]:
np.empty([5,5])

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [58]:
np.random.rand()

0.42813604221688084

In [64]:
[np.round(np.random.rand()*10) for item in range(10)]

[6.0, 8.0, 2.0, 8.0, 5.0, 9.0, 7.0, 8.0, 2.0, 9.0]

In [66]:
np.random.randint(5)

4

In [68]:
[np.random.randint(5)for item in range(10)]

[1, 4, 1, 1, 3, 1, 0, 0, 4, 2]

In [70]:
np.random.seed = 0
[np.random.randint(5)for item in range(10)]

[1, 2, 4, 2, 4, 3, 4, 2, 4, 2]

In [71]:
np.random.rand(5,5)

array([[0.91396202, 0.45720481, 0.43069857, 0.93912779, 0.77838924],
       [0.71597052, 0.8027575 , 0.09280081, 0.51815255, 0.86502025],
       [0.82914691, 0.82960336, 0.27304997, 0.0592432 , 0.67052804],
       [0.59306552, 0.6716541 , 0.41178788, 0.1975509 , 0.28962964],
       [0.14212014, 0.78331447, 0.41253884, 0.03417131, 0.62402999]])

In [72]:
np.round(np.random.rand(5,5))

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 1., 1.]])

In [73]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([1, 8, 2, 4, 9])

In [74]:
np_matrix = np.random.rand(5,5)
np_matrix

array([[0.90340192, 0.1374747 , 0.13927635, 0.80739129, 0.39767684],
       [0.1653542 , 0.92750858, 0.34776586, 0.7508121 , 0.72599799],
       [0.88330609, 0.62367221, 0.75094243, 0.34889834, 0.26992789],
       [0.89588622, 0.42809119, 0.96484005, 0.6634415 , 0.62169572],
       [0.11474597, 0.94948926, 0.44991213, 0.57838961, 0.4081368 ]])

In [78]:
idx_choose = np.round(np.random.choice(5,3, replace=False))
idx_choose

array([2, 4, 1])

In [79]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.88330609, 0.62367221, 0.75094243, 0.34889834, 0.26992789],
       [0.11474597, 0.94948926, 0.44991213, 0.57838961, 0.4081368 ],
       [0.1653542 , 0.92750858, 0.34776586, 0.7508121 , 0.72599799]])

Homewoek Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [80]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np_matrix[:,4])
np_matrix

array([[0.69089692, 0.99732285, 0.17234051, 0.13713575, 1.        ],
       [0.69681816, 0.06600017, 0.75546305, 0.75387619, 1.        ],
       [0.71152476, 0.12427096, 0.01988013, 0.02621099, 0.        ],
       [0.24621107, 0.86002795, 0.53883106, 0.55282198, 1.        ],
       [0.12417332, 0.27918368, 0.58575927, 0.96959575, 1.        ],
       [0.01864729, 0.80063267, 0.23297427, 0.8071052 , 0.        ],
       [0.86354185, 0.74712164, 0.55624023, 0.13645523, 0.        ],
       [0.12134346, 0.04455188, 0.10749413, 0.22570934, 1.        ],
       [0.55971698, 0.01255598, 0.07197428, 0.96727633, 1.        ],
       [0.20329323, 0.25232574, 0.74382585, 0.19542948, 1.        ]])

In [81]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 3,  5,  3,  2,  4],
       [ 4,  0,  3,  3,  8],
       [ 3,  5,  6,  7,  5],
       [ 1,  7,  0, 10, 10],
       [ 2,  8,  2,  1,  4]])

In [82]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 0, 0, 2, 1],
       [1, 0, 2, 2, 1],
       [2, 1, 2, 1, 2],
       [0, 0, 2, 2, 0],
       [1, 2, 0, 2, 0]])

In [86]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 3),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 2),
 (2, 4),
 (3, 2),
 (3, 3),
 (4, 1),
 (4, 3)]

In [87]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(row))]

[(0, 3),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 2),
 (2, 4),
 (3, 2),
 (3, 3),
 (4, 1),
 (4, 3)]

Homework Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[idx,:]

In [90]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([1, 2, 0, 2, 0])

In [91]:
idx = [1,2,3,4,5]
idx

[1, 2, 3, 4, 5]

In [98]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 0, 2, 2, 0],
       [1, 1, 2, 1, 2],
       [0, 1, 1, 0, 1],
       [1, 2, 2, 0, 2],
       [0, 2, 0, 2, 2]])

In [99]:
rng = np.random.RandomState(0)
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 2, 0, 2, 0],
       [1, 2, 1, 0, 2],
       [2, 2, 0, 1, 2],
       [1, 1, 1, 1, 0],
       [1, 2, 1, 0, 0]])

In [100]:
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[1, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 2, 2, 0, 1],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [101]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

In [102]:
rng = np.random.RandomState(22)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[1, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 2, 2, 0, 1],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [103]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 1, 2, 1],
       [0, 0, 1, 0, 2]])

In [104]:
np_matrix = np.delete(np_matrix,[1,1],0)
np_matrix

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 2]])

In [105]:
a = np_matrix == 2
a

array([[False, False, False, False, False],
       [False, False, False, False,  True]])

In [106]:
np_matrix[a] = 99
np_matrix

array([[ 1,  0,  0,  0,  0],
       [ 0,  0,  1,  0, 99]])

In [107]:
np_matrix [np_matrix == 2] =99
np_matrix

array([[ 1,  0,  0,  0,  0],
       [ 0,  0,  1,  0, 99]])

Homework Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
#Then, randomly create a label vector for 10 samples. 
#Finally, seperate samples into 2 groups
#Group 1 called train_data (label == 0)
#Group 2 called test_data (label == 1)

In [108]:
matrix = np.random.randint(10,size = (10,5))
matrix

array([[2, 9, 4, 0, 0],
       [3, 4, 9, 3, 9],
       [1, 2, 5, 4, 0],
       [8, 2, 3, 9, 9],
       [4, 4, 8, 2, 1],
       [6, 3, 8, 9, 7],
       [0, 5, 2, 2, 8],
       [5, 0, 5, 9, 8],
       [6, 6, 0, 4, 7],
       [3, 0, 1, 6, 0]])

In [109]:
label_vector = np.random.randint(2,size = 10)
label_vector

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [110]:
train_data = matrix[np.where(label_vector == 0)]
train_data

array([[2, 9, 4, 0, 0],
       [1, 2, 5, 4, 0],
       [8, 2, 3, 9, 9],
       [4, 4, 8, 2, 1],
       [0, 5, 2, 2, 8],
       [6, 6, 0, 4, 7],
       [3, 0, 1, 6, 0]])

In [111]:
test_data = matrix[np.where(label_vector == 1)]
test_data

array([[3, 4, 9, 3, 9],
       [6, 3, 8, 9, 7],
       [5, 0, 5, 9, 8]])